### PR TITLE
docs: Fix a few copy issues in avoiding-n-plus-1s.md

### PR DESCRIPTION
**Pull request by albertchae**
Hi, just fixing some typos I noticed while reading this page. Thanks for writing a great general overview on N+1s and how Joist specifically addresses them!

### CODE REVIEW

**Comment by stephenh** [comment]
Nice, this is great @albertchae , thank you!

**Comment by stephenh** [comment]
Fwiw @albertchae we've really not done a lot of promotion of Joist yet, so wondering how you came across us? Just googling for typescript n+1 issues? Just curious!

We need to do more posting / devrel / etc., but it's just easy for it to keep slipping down the todo list. :-)

**Comment by albertchae** [comment]
> Fwiw @albertchae we've really not done a lot of promotion of Joist yet, so wondering how you came across us? Just googling for typescript n+1 issues? Just curious!
> 
> We need to do more posting / devrel / etc., but it's just easy for it to keep slipping down the todo list. :-)

@stephenh I listened to your appearance on https://changelog.com/jsparty/276 last year and thought the lazy batching of queries to avoid N+1s sounded clever, but I haven't worked on a JS backend in a while so I didn't actually try out Joist. More recently I was looking into dataloader for ruby-graphql and it reminded me of that podcast episode, so I looked into your docs and realized that you were using dataloader too 😛 . I thought this page is a pretty good overview of the N+1 problem in general so I'm going to table it away as a linkable reference, and if I ever do work on a JS backend again I'll definitely try out the ORM!

**Comment by stephenh** [comment]
@albertchae nice! Thanks for the reply; that makes sense & yep, if you end up w/a node backend, hope to see how/if Joist works out for you. :-)

**Pull request merged**
